### ISSUE TITLE
Question about evaluation metrics

### ISSUE THREAD

**Issue by huiwenn** [lilys012/AmbigDocs#1]
Hi! 

thank you for putting this dataset together; it is really helpful to our research :) 

I want to ask about the method names in the `eval.py` script: 

- is "R" answer recall, and "Entity" entity recall?
- is there existing code for the answer-entity recall (EAR) metric you report in the paper?
 
(I could implement myself using the two if i'm understanding correctly, but I thought I should ask. )

Thank you!

Best,
Sophia

**Comment by lilys012** [comment]
Hi, thank you for your interest! 

As you have correctly pointed out, 'R' stands for answer recall and 'Entity' stands for entity recall.

Also, 'EWR' stands for answer-entity recall. I'll try to revise the acronyms to sound more clearly :)

**Comment by huiwenn** [comment]
I see. Thank you for your quick response!
